language: php
dist: trusty
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm
sudo: false
matrix:
  allow_failures:
    - php:
      - nightly
cache:
  directories:
    - vendor
install:
  - composer install --prefer-dist
script:
  - bash run-travis
