language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm
sudo: false
matrix:
  allow_failures:
    - php:
      - nightly
install:
  - composer install --prefer-dist
script:
  - run-travis
